#########################################
#  Highlight                            #
#  https://gitlab.com/saalen/highlight  #
#########################################

dist: trusty

git:
  depth: false

install:
  - npm install -g eclint

script:
  - eclint check
